version: '3.3'

services:  
    frontend:
        build:
            context: frontend/
        container_name: frontend-vue
        ports:
            - 8080:8080
            - 80:80
        networks: 
            - deploy
        environment:
            - VUE_APP_BASE_URL=http://34.201.252.160/v1   
networks:
    deploy:
        driver: bridge